package de.dhbw.corona_world_app.datastructure.displayables;

import de.dhbw.corona_world_app.datastructure.Displayable;

public enum ISOCountry implements Displayable {

    Afghanistan("AF","Afghanistan", com.michaelfotiadis.androidflags.R.drawable.ic_list_country_af),
    Aland_Islands("AX","Åland Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ax),
    Albania("AL","Albania",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_al),
    Algeria("DZ","Algeria",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_dz),
    American_Samoa("AS","American Samoa",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_as),
    Andorra("AD","Andorra",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ad),
    Angola("AO","Angola",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ao),
    Anguilla("AI","Anguilla",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ai),
    Antarctica("AQ","Antarctica",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_aq),
    Antigua_and_Barbuda("AG","Antigua and Barbuda",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ag),
    Argentina("AR","Argentina",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ar),
    Armenia("AM","Armenia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_am),
    Aruba("AW","Aruba",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_aw),
    Australia("AU","Australia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_au),
    Austria("AT","Austria",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_at),
    Azerbaijan("AZ","Azerbaijan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_az),
    Bahamas("BS","Bahamas",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bs),
    Bahrain("BH","Bahrain",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bh),
    Bangladesh("BD","Bangladesh",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bd),
    Barbados("BB","Barbados",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bb),
    Belarus("BY","Belarus",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_by),
    Belgium("BE","Belgium",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_be),
    Belize("BZ","Belize",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bz),
    Benin("BJ","Benin",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bj),
    Bermuda("BM","Bermuda",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bm),
    Bhutan("BT","Bhutan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bt),
    Bolivia("BO","Bolivia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bo),
    Bonaire_Sint_Eustatius_and_Saba("BQ","Bonaire, Sint Eustatius and Saba",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_nl),
    Bosnia_and_Herzegovina("BA","Bosnia and Herzegovina",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ba),
    Botswana("BW","Botswana",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bw),
    Bouvet_Island("BV","Bouvet Island",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_no),
    Brazil("BR","Brazil",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_br),
    British_Indian_Ocean_Territory("IO","British Indian Ocean Territory",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_unknown),
    Brunei_Darussalam("BN","Brunei Darussalam",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bn),
    Bulgaria("BG","Bulgaria",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bg),
    Burkina_Faso("BF","Burkina Faso",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bf),
    Burundi("BI","Burundi",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bi),
    Cabo_Verde("KH","Cambodia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_kh),
    Cambodia("CM","Cameroon",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cm),
    Cameroon("CA","Canada",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ca),
    Canada("CV","Cape Verde",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cv),
    Cayman_Islands("KY","Cayman Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ky),
    Central_African_Republic("CF","Central African Republic",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cf),
    Chad("TD","Chad",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_td),
    Chile("CL","Chile",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cl),
    China("CN","China",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cn),
    Christmas_Island("CX","Christmas Island",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cx),
    Cocos("CC","Cocos (Keeling) Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cc),
    Colombia("CO","Colombia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_co),
    Comoros("KM","Comoros",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_km),
    Congo("CG","Congo",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cg),
    Democratic_Republic_Congo("CD","Democratic Republic of the Congo",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cd),
    Cook_Islands("CK","Cook Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ck),
    Costa_Rica("CR","Costa Rica",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cr),
    C_te_d_Ivoire("CI","Ivory Coast",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ci),
    Croatia("HR","Croatia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_hr),
    Cuba("CU","Cuba",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cu),
    Cura_ao("CW","Curaçao",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cw),
    Cyprus("CY","Cyprus",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cy),
    Czechia("CZ","Czech Republic",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_cz),
    Denmark("DK","Denmark",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_dk),
    Djibouti("DJ","Djibouti",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_dj),
    Dominica("DM","Dominica",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_dm),
    Dominican_Republic("DO","Dominican Republic",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_do),
    Ecuador("EC","Ecuador",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ec),
    Egypt("EG","Egypt",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_eg),
    El_Salvador("SV","El Salvador",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sv),
    Equatorial_Guinea("GQ","Equatorial Guinea",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gq),
    Eritrea("ER","Eritrea",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_er),
    Estonia("EE","Estonia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ee),
    Ethiopia("ET","Ethiopia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_et),
    Falkland_Islands("FK","Falkland Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_fk),
    Faroe_Islands("FO","Faroe Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_fo),
    Fiji("FJ","Fiji",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_fj),
    Finland("FI","Finland",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_fi),
    France("FR","France",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_fr),
    French_Guiana("GF","French Guiana",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_fr),
    French_Polynesia("PF","French Polynesia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_pf),
    French_Southern_Territories("TF","French Southern Territories",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tf),
    Gabon("GA","Gabon",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ga),
    Gambia("GM","Gambia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gm),
    Georgia("GE","Georgia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ge),
    Germany("DE","Germany",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_de),
    Ghana("GH","Ghana",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gh),
    Gibraltar("GI","Gibraltar",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gi),
    Greece("GR","Greece",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gr),
    Greenland("GL","Greenland",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gl),
    Grenada("GD","Grenada",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gd),
    Guadeloupe("GP","Guadeloupe",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_fr),
    Guam("GU","Guam",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gu),
    Guatemala("GT","Guatemala",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gt),
    Guernsey("GG","Guernsey",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gg),
    Guinea("GN","Guinea",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gn),
    Guinea_Bissau("GW","Guinea-Bissau",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gw),
    Guyana("GY","Guyana",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gy),
    Haiti("HT","Haiti",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ht),
    Heard_Island_and_McDonald_Islands("HM","Heard Island and McDonald Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_unknown),
    Holy_See("VA","Holy See (Vatican City State)",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_va),
    Honduras("HN","Honduras",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_hn),
    Hong_Kong("HK","Hong Kong",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_hk),
    Hungary("HU","Hungary",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_hu),
    Iceland("IS","Iceland",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_is),
    India("IN","India",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_in),
    Indonesia("ID","Indonesia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_id),
    Iran("IR","Iran",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ir),
    Iraq("IQ","Iraq",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_iq),
    Ireland("IE","Ireland",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ie),
    Isle_of_Man("IM","Isle of Man",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_im),
    Israel("IL","Israel",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_il),
    Italy("IT","Italy",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_it),
    Jamaica("JM","Jamaica",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_jm),
    Japan("JP","Japan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_jp),
    Jersey("JE","Jersey",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_je),
    Jordan("JO","Jordan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_jo),
    Kazakhstan("KZ","Kazakhstan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_kz),
    Kenya("KE","Kenya",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ke),
    Kiribati("KI","Kiribati",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ki),
    North_Korea("KP","North Korea",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_kp),
    South_Korea("KR","South Korea",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_kr),
    Kuwait("KW","Kuwait",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_kw),
    Kyrgyzstan("KG","Kyrgyzstan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_kg),
    Lao_People_s_Democratic_Republic("LA","Laos",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_la),
    Latvia("LV","Latvia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_lv),
    Lebanon("LB","Lebanon",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_lb),
    Lesotho("LS","Lesotho",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ls),
    Liberia("LR","Liberia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_lr),
    Libya("LY","Libya",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ly),
    Liechtenstein("LI","Liechtenstein",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_li),
    Lithuania("LT","Lithuania",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_lt),
    Luxembourg("LU","Luxembourg",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_lu),
    Macao("MO","Macao",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mo),
    Macedonia("MK","Macedonia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mk),
    Madagascar("MG","Madagascar",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mg),
    Malawi("MW","Malawi",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mw),
    Malaysia("MY","Malaysia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_my),
    Maldives("MV","Maldives",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mv),
    Mali("ML","Mali",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ml),
    Malta("MT","Malta",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mt),
    Marshall_Islands("MH","Marshall Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mh),
    Martinique("MQ","Martinique",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mq),
    Mauritania("MR","Mauritania",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mr),
    Mauritius("MU","Mauritius",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mu),
    Mayotte("YT","Mayotte",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_yt),
    Mexico("MX","Mexico",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mx),
    Micronesia("FM","Micronesia (Federated States of)",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_fm),
    Moldova("MD","Moldova",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_md),
    Monaco("MC","Monaco",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mc),
    Mongolia("MN","Mongolia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mn),
    Montenegro("ME","Montenegro",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_me),
    Montserrat("MS","Montserrat",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ms),
    Morocco("MA","Morocco",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ma),
    Mozambique("MZ","Mozambique",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mz),
    Myanmar("MM","Myanmar",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mm),
    Namibia("NA","Namibia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_na),
    Nauru("NR","Nauru",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_nr),
    Nepal("NP","Nepal",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_np),
    Netherlands("NL","Netherlands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_nl),
    New_Caledonia("NC","New Caledonia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_nc),
    New_Zealand("NZ","New Zealand",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_nz),
    Nicaragua("NI","Nicaragua",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ni),
    Niger("NE","Niger",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ne),
    Nigeria("NG","Nigeria",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ng),
    Niue("NU","Niue",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_nu),
    Norfolk_Island("NF","Norfolk Island",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_nf),
    Northern_Mariana_Islands("MP","Northern Mariana Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mp),
    Norway("NO","Norway",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_no),
    Oman("OM","Oman",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_om),
    Pakistan("PK","Pakistan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_pk),
    Palau("PW","Palau",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_pw),
    Palestine_State_of("PS","Palestine, State of",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ps),
    Panama("PA","Panama",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_pa),
    Papua_New_Guinea("PG","Papua New Guinea",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_pg),
    Paraguay("PY","Paraguay",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_py),
    Peru("PE","Peru",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_pe),
    Philippines("PH","Philippines",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ph),
    Pitcairn("PN","Pitcairn",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_pn),
    Poland("PL","Poland",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_pl),
    Portugal("PT","Portugal",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_pt),
    Puerto_Rico("PR","Puerto Rico",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_pr),
    Qatar("QA","Qatar",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_qa),
    R_union("RE","Reunion",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_fr),
    Romania("RO","Romania",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ro),
    Russian_Federation("RU","Russia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ru),
    Rwanda("RW","Rwanda",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_rw),
    Saint_Barth_lemy("BL","Saint Barthélemy",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_bl),
    Saint_Helena_Ascension_and_Tristan_da_Cunha("SH","Saint Helena, Ascension and Tristan da Cunha",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sh),
    Saint_Kitts_and_Nevis("KN","Saint Kitts and Nevis",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_kn),
    Saint_Lucia("LC","Saint Lucia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_lc),
    Saint_Martin("MF","Saint Martin (French part)",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_mf),
    Saint_Pierre_and_Miquelon("PM","Saint Pierre and Miquelon",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_fr),
    Saint_Vincent_and_the_Grenadines("VC","Saint Vincent and the Grenadines",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_vc),
    Samoa("WS","Samoa",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ws),
    San_Marino("SM","San Marino",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sm),
    Sao_Tome_and_Principe("ST","Sao Tome and Principe",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_st),
    Saudi_Arabia("SA","Saudi Arabia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sa),
    Senegal("SN","Senegal",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sn),
    Serbia("RS","Serbia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_rs),
    Seychelles("SC","Seychelles",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sc),
    Sierra_Leone("SL","Sierra Leone",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sl),
    Singapore("SG","Singapore",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sg),
    Sint_Maarten("SX","Sint Maarten (Dutch part)",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_unknown),
    Slovakia("SK","Slovakia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sk),
    Slovenia("SI","Slovenia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_si),
    Solomon_Islands("SB","Solomon Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sb),
    Somalia("SO","Somalia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_so),
    South_Africa("ZA","South Africa",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_za),
    South_Georgia_and_the_South_Sandwich_Islands("GS","South Georgia and the South Sandwich Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gs),
    South_Sudan("SS","South Sudan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ss),
    Spain("ES","Spain",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_es),
    Sri_Lanka("LK","Sri Lanka",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_lk),
    Sudan("SD","Sudan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sd),
    Suriname("SR","Suriname",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sr),
    Svalbard_and_Jan_Mayen("SJ","Svalbard",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_unknown),
    Swaziland("SZ","Swaziland",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sz),
    Sweden("SE","Sweden",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_se),
    Switzerland("CH","Switzerland",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ch),
    Syrian_Arab_Republic("SY","Syria",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_sy),
    Taiwan_Province_of_China("TW","Taiwan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tw),
    Tajikistan("TJ","Tajikistan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tj),
    Tanzania_United_Republic_of("TZ","Tanzania",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tz),
    Thailand("TH","Thailand",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_th),
    Timor_Leste("TL","Timor Leste",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tl),
    Togo("TG","Togo",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tg),
    Tokelau("TK","Tokelau",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tk),
    Tonga("TO","Tonga",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_to),
    Trinidad_and_Tobago("TT","Trinidad and Tobago",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tt),
    Tunisia("TN","Tunisia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tn),
    Turkey("TR","Turkey",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tr),
    Turkmenistan("TM","Turkmenistan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tm),
    Turks_and_Caicos_Islands("TC","Turks and Caicos Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tc),
    Tuvalu("TV","Tuvalu",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_tv),
    Uganda("UG","Uganda",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ug),
    Ukraine("UA","Ukraine",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ua),
    United_Arab_Emirates("AE","United Arab Emirates",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ae),
    United_Kingdom_of_Great_Britain_and_Northern_Ireland("GB","United Kingdom",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_gb),
    United_States_of_America("US","United States",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_us),
    United_States_Minor_Outlying_Islands("UM","United States Minor Outlying Islands",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_us),
    Uruguay("UY","Uruguay",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_uy),
    Uzbekistan("UZ","Uzbekistan",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_uz),
    Vanuatu("VU","Vanuatu",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_vu),
    Venezuela("VE","Venezuela",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ve),
    Viet_Nam("VN","Vietnam",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_vn),
    British_Virgin_Islands("VG","Virgin Islands (British)",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_vg),
    US_Virgin_Islands("VI","Virgin Islands (U.S.)",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_vi),
    Wallis_and_Futuna("WF","Wallis and Futuna",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_wf),
    Western_Sahara("EH","Western Sahara",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_eh),
    Republic_of_Kosovo("XK","Kosovo",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_kosovo),
    Yemen("YE","Yemen",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_ye),
    Zambia("ZM","Zambia",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_zm),
    Zimbabwe("ZW","Zimbabwe",com.michaelfotiadis.androidflags.R.drawable.ic_list_country_zw),
    World("WW", "World", com.michaelfotiadis.androidflags.R.drawable.ic_list_country_unknown);

    private final String ISOCode;
    private final String displayName;
    private final int flagDrawableID;

    ISOCountry(String ISOCode,String displayName,int flagDrawableID) {
        this.ISOCode = ISOCode;
        this.displayName=displayName;
        this.flagDrawableID = flagDrawableID;
    }

    public String getISOCode() {
        return this.ISOCode;
    }

    public String getDisplayName(){return this.displayName;}

    public int getFlagDrawableID() {
        return flagDrawableID;
    }

    @Override
    public String toString() {
        return getDisplayName();
    }

}
