package de.dhbw.corona_world_app.datastructure.displayables;

import androidx.annotation.NonNull;

import de.dhbw.corona_world_app.datastructure.Displayable;

public enum ISOCountry implements Displayable {

    Afghanistan("AF", "Afghanistan"),
    Aland_Islands("AX", "Åland Islands"),
    Albania("AL", "Albania"),
    Algeria("DZ", "Algeria"),
    American_Samoa("AS", "American Samoa"),
    Andorra("AD", "Andorra"),
    Angola("AO", "Angola"),
    Anguilla("AI", "Anguilla"),
    Antarctica("AQ", "Antarctica"),
    Antigua_and_Barbuda("AG", "Antigua and Barbuda"),
    Argentina("AR", "Argentina"),
    Armenia("AM", "Armenia"),
    Aruba("AW", "Aruba"),
    Australia("AU", "Australia"),
    Austria("AT", "Austria"),
    Azerbaijan("AZ", "Azerbaijan"),
    Bahamas("BS", "Bahamas"),
    Bahrain("BH", "Bahrain"),
    Bangladesh("BD", "Bangladesh"),
    Barbados("BB", "Barbados"),
    Belarus("BY", "Belarus"),
    Belgium("BE", "Belgium"),
    Belize("BZ", "Belize"),
    Benin("BJ", "Benin"),
    Bermuda("BM", "Bermuda"),
    Bhutan("BT", "Bhutan"),
    Bolivia("BO", "Bolivia"),
    Bonaire_Sint_Eustatius_and_Saba("BQ", "Bonaire, Sint Eustatius and Saba"),
    Bosnia_and_Herzegovina("BA", "Bosnia and Herzegovina"),
    Botswana("BW", "Botswana"),
    Bouvet_Island("BV", "Bouvet Island"),
    Brazil("BR", "Brazil"),
    British_Indian_Ocean_Territory("IO", "British Indian Ocean Territory"),
    Brunei_Darussalam("BN", "Brunei Darussalam"),
    Bulgaria("BG", "Bulgaria"),
    Burkina_Faso("BF", "Burkina Faso"),
    Burundi("BI", "Burundi"),
    Cabo_Verde("KH", "Cambodia"),
    Cambodia("CM", "Cameroon"),
    Cameroon("CA", "Canada"),
    Canada("CV", "Cape Verde"),
    Cayman_Islands("KY", "Cayman Islands"),
    Central_African_Republic("CF", "Central African Republic"),
    Chad("TD", "Chad"),
    Chile("CL", "Chile"),
    China("CN", "China"),
    Christmas_Island("CX", "Christmas Island"),
    Cocos("CC", "Cocos (Keeling) Islands"),
    Colombia("CO", "Colombia"),
    Comoros("KM", "Comoros"),
    Congo("CG", "Congo"),
    Democratic_Republic_Congo("CD", "Democratic Republic of the Congo"),
    Cook_Islands("CK", "Cook Islands"),
    Costa_Rica("CR", "Costa Rica"),
    C_te_d_Ivoire("CI", "Ivory Coast"),
    Croatia("HR", "Croatia"),
    Cuba("CU", "Cuba"),
    Cura_ao("CW", "Curaçao"),
    Cyprus("CY", "Cyprus"),
    Czechia("CZ", "Czech Republic"),
    Denmark("DK", "Denmark"),
    Djibouti("DJ", "Djibouti"),
    Dominica("DM", "Dominica"),
    Dominican_Republic("DO", "Dominican Republic"),
    Ecuador("EC", "Ecuador"),
    Egypt("EG", "Egypt"),
    El_Salvador("SV", "El Salvador"),
    Equatorial_Guinea("GQ", "Equatorial Guinea"),
    Eritrea("ER", "Eritrea"),
    Estonia("EE", "Estonia"),
    Ethiopia("ET", "Ethiopia"),
    Falkland_Islands("FK", "Falkland Islands"),
    Faroe_Islands("FO", "Faroe Islands"),
    Fiji("FJ", "Fiji"),
    Finland("FI", "Finland"),
    France("FR", "France"),
    French_Guiana("GF", "French Guiana"),
    French_Polynesia("PF", "French Polynesia"),
    French_Southern_Territories("TF", "French Southern Territories"),
    Gabon("GA", "Gabon"),
    Gambia("GM", "Gambia"),
    Georgia("GE", "Georgia"),
    Germany("DE", "Germany"),
    Ghana("GH", "Ghana"),
    Gibraltar("GI", "Gibraltar"),
    Greece("GR", "Greece"),
    Greenland("GL", "Greenland"),
    Grenada("GD", "Grenada"),
    Guadeloupe("GP", "Guadeloupe"),
    Guam("GU", "Guam"),
    Guatemala("GT", "Guatemala"),
    Guernsey("GG", "Guernsey"),
    Guinea("GN", "Guinea"),
    Guinea_Bissau("GW", "Guinea-Bissau"),
    Guyana("GY", "Guyana"),
    Haiti("HT", "Haiti"),
    Heard_Island_and_McDonald_Islands("HM", "Heard Island and McDonald Islands"),
    Holy_See("VA", "Holy See (Vatican City State)"),
    Honduras("HN", "Honduras"),
    Hong_Kong("HK", "Hong Kong"),
    Hungary("HU", "Hungary"),
    Iceland("IS", "Iceland"),
    India("IN", "India"),
    Indonesia("ID", "Indonesia"),
    Iran("IR", "Iran"),
    Iraq("IQ", "Iraq"),
    Ireland("IE", "Ireland"),
    Isle_of_Man("IM", "Isle of Man"),
    Israel("IL", "Israel"),
    Italy("IT", "Italy"),
    Jamaica("JM", "Jamaica"),
    Japan("JP", "Japan"),
    Jersey("JE", "Jersey"),
    Jordan("JO", "Jordan"),
    Kazakhstan("KZ", "Kazakhstan"),
    Kenya("KE", "Kenya"),
    Kiribati("KI", "Kiribati"),
    North_Korea("KP", "North Korea"),
    South_Korea("KR", "South Korea"),
    Kuwait("KW", "Kuwait"),
    Kyrgyzstan("KG", "Kyrgyzstan"),
    Lao_People_s_Democratic_Republic("LA", "Laos"),
    Latvia("LV", "Latvia"),
    Lebanon("LB", "Lebanon"),
    Lesotho("LS", "Lesotho"),
    Liberia("LR", "Liberia"),
    Libya("LY", "Libya"),
    Liechtenstein("LI", "Liechtenstein"),
    Lithuania("LT", "Lithuania"),
    Luxembourg("LU", "Luxembourg"),
    Macao("MO", "Macao"),
    Macedonia("MK", "Macedonia"),
    Madagascar("MG", "Madagascar"),
    Malawi("MW", "Malawi"),
    Malaysia("MY", "Malaysia"),
    Maldives("MV", "Maldives"),
    Mali("ML", "Mali"),
    Malta("MT", "Malta"),
    Marshall_Islands("MH", "Marshall Islands"),
    Martinique("MQ", "Martinique"),
    Mauritania("MR", "Mauritania"),
    Mauritius("MU", "Mauritius"),
    Mayotte("YT", "Mayotte"),
    Mexico("MX", "Mexico"),
    Micronesia("FM", "Micronesia (Federated States of)"),
    Moldova("MD", "Moldova"),
    Monaco("MC", "Monaco"),
    Mongolia("MN", "Mongolia"),
    Montenegro("ME", "Montenegro"),
    Montserrat("MS", "Montserrat"),
    Morocco("MA", "Morocco"),
    Mozambique("MZ", "Mozambique"),
    Myanmar("MM", "Myanmar"),
    Namibia("NA", "Namibia"),
    Nauru("NR", "Nauru"),
    Nepal("NP", "Nepal"),
    Netherlands("NL", "Netherlands"),
    New_Caledonia("NC", "New Caledonia"),
    New_Zealand("NZ", "New Zealand"),
    Nicaragua("NI", "Nicaragua"),
    Niger("NE", "Niger"),
    Nigeria("NG", "Nigeria"),
    Niue("NU", "Niue"),
    Norfolk_Island("NF", "Norfolk Island"),
    Northern_Mariana_Islands("MP", "Northern Mariana Islands"),
    Norway("NO", "Norway"),
    Oman("OM", "Oman"),
    Pakistan("PK", "Pakistan"),
    Palau("PW", "Palau"),
    Palestine_State_of("PS", "Palestine, State of"),
    Panama("PA", "Panama"),
    Papua_New_Guinea("PG", "Papua New Guinea"),
    Paraguay("PY", "Paraguay"),
    Peru("PE", "Peru"),
    Philippines("PH", "Philippines"),
    Pitcairn("PN", "Pitcairn"),
    Poland("PL", "Poland"),
    Portugal("PT", "Portugal"),
    Puerto_Rico("PR", "Puerto Rico"),
    Qatar("QA", "Qatar"),
    R_union("RE", "Reunion"),
    Romania("RO", "Romania"),
    Russian_Federation("RU", "Russia"),
    Rwanda("RW", "Rwanda"),
    Saint_Barth_lemy("BL", "Saint Barthélemy"),
    Saint_Helena_Ascension_and_Tristan_da_Cunha("SH", "Saint Helena, Ascension and Tristan da Cunha"),
    Saint_Kitts_and_Nevis("KN", "Saint Kitts and Nevis"),
    Saint_Lucia("LC", "Saint Lucia"),
    Saint_Martin("MF", "Saint Martin (French part)"),
    Saint_Pierre_and_Miquelon("PM", "Saint Pierre and Miquelon"),
    Saint_Vincent_and_the_Grenadines("VC", "Saint Vincent and the Grenadines"),
    Samoa("WS", "Samoa"),
    San_Marino("SM", "San Marino"),
    Sao_Tome_and_Principe("ST", "Sao Tome and Principe"),
    Saudi_Arabia("SA", "Saudi Arabia"),
    Senegal("SN", "Senegal"),
    Serbia("RS", "Serbia"),
    Seychelles("SC", "Seychelles"),
    Sierra_Leone("SL", "Sierra Leone"),
    Singapore("SG", "Singapore"),
    Sint_Maarten("SX", "Sint Maarten (Dutch part)"),
    Slovakia("SK", "Slovakia"),
    Slovenia("SI", "Slovenia"),
    Solomon_Islands("SB", "Solomon Islands"),
    Somalia("SO", "Somalia"),
    South_Africa("ZA", "South Africa"),
    South_Georgia_and_the_South_Sandwich_Islands("GS", "South Georgia and the South Sandwich Islands"),
    South_Sudan("SS", "South Sudan"),
    Spain("ES", "Spain"),
    Sri_Lanka("LK", "Sri Lanka"),
    Sudan("SD", "Sudan"),
    Suriname("SR", "Suriname"),
    Svalbard_and_Jan_Mayen("SJ", "Svalbard"),
    Swaziland("SZ", "Swaziland"),
    Sweden("SE", "Sweden"),
    Switzerland("CH", "Switzerland"),
    Syrian_Arab_Republic("SY", "Syria"),
    Taiwan_Province_of_China("TW", "Taiwan"),
    Tajikistan("TJ", "Tajikistan"),
    Tanzania_United_Republic_of("TZ", "Tanzania"),
    Thailand("TH", "Thailand"),
    Timor_Leste("TL", "Timor Leste"),
    Togo("TG", "Togo"),
    Tokelau("TK", "Tokelau"),
    Tonga("TO", "Tonga"),
    Trinidad_and_Tobago("TT", "Trinidad and Tobago"),
    Tunisia("TN", "Tunisia"),
    Turkey("TR", "Turkey"),
    Turkmenistan("TM", "Turkmenistan"),
    Turks_and_Caicos_Islands("TC", "Turks and Caicos Islands"),
    Tuvalu("TV", "Tuvalu"),
    Uganda("UG", "Uganda"),
    Ukraine("UA", "Ukraine"),
    United_Arab_Emirates("AE", "United Arab Emirates"),
    United_Kingdom_of_Great_Britain_and_Northern_Ireland("GB", "United Kingdom"),
    United_States_of_America("US", "United States"),
    United_States_Minor_Outlying_Islands("UM", "United States Minor Outlying Islands"),
    Uruguay("UY", "Uruguay"),
    Uzbekistan("UZ", "Uzbekistan"),
    Vanuatu("VU", "Vanuatu"),
    Venezuela("VE", "Venezuela"),
    Viet_Nam("VN", "Vietnam"),
    British_Virgin_Islands("VG", "Virgin Islands (British)"),
    US_Virgin_Islands("VI", "Virgin Islands (U.S.)"),
    Wallis_and_Futuna("WF", "Wallis and Futuna"),
    Western_Sahara("EH", "Western Sahara"),
    Republic_of_Kosovo("XK", "Kosovo"),
    Yemen("YE", "Yemen"),
    Zambia("ZM", "Zambia"),
    Zimbabwe("ZW", "Zimbabwe");

    private final String ISOCode;
    private final String displayName;

    ISOCountry(String ISOCode, String displayName) {
        this.ISOCode = ISOCode;
        this.displayName = displayName;
    }

    public String getISOCode() {
        return this.ISOCode;
    }

    public String getDisplayName() {
        return this.displayName;
    }

    @Override
    public String toString() {
        return getDisplayName();
    }

}
